// Liste des citations avec balises HTML pour styliser certains mots
const citations = [
	"Les super-héros, du plus au moins susceptible de gagner un concours de cuisine",
	"De la pire à la meilleure façon de s'excuser",
	"Les aliments que vous voulez le moins au plus dans une apocalypse zombie",
	"Les objets que vous voulez le plus au moins si vous êtes coincé dans l'espace",
	"Les pires aux meilleures choses à renverser sur vous-même",
	"Les choses qui rendent quelqu'un le moins au plus susceptible de devenir un super-vilain",
	"Les villes du plus au moins futuriste",
	"Les pires aux meilleures choses à dire lors d'un entretien d'embauche",
	"Les films du moins au plus susceptibles de vous confondre",
	"Les objets fictifs que vous voulez le plus au moins dans la vie réelle",
	"Les pires aux meilleurs moments pour perdre votre voix",
	"Les animaux du moins au plus photogénique",
	"Les super-pouvoirs du moins au plus gênant",
	"Les célébrités du moins au plus susceptibles de survivre à une apocalypse zombie",
	"Les pires aux meilleures choses à regarder en rafale",
	"Les aliments du moins au plus dangereux à manger en conduisant",
	"Les chansons du moins au plus susceptibles de rester dans votre tête",
	"Les méchants fictifs du moins au plus incompris",
	"Les pires aux meilleures choses à envoyer accidentellement à votre patron",
	"Les animaux du moins au plus susceptibles d'être bons en stand-up",
	"Les super-héros du moins au plus susceptibles d'oublier votre anniversaire",
	"Les films du moins au plus susceptibles d'inspirer un mème",
	"Les lieux fictifs que vous voulez le moins au plus visiter en vacances",
	"Les aliments du pire au meilleur à manger avec les mains",
	"Les célébrités du moins au plus susceptibles d'organiser un dîner chaotique",
	"Les créatures fictives du moins au plus câlin",
	"Les pires aux meilleures excuses pour annuler des plans à la dernière minute",
	"Les choses que vous voulez le moins au plus faire tomber de votre poche",
	"Les pires aux meilleures choses à trouver dans votre placard",
	"Les figures historiques du moins au plus susceptibles d'être technophiles",
	"Les pires aux meilleures choses à se produire lors d'un road trip",
	"Les choses que vous voulez le moins au plus rencontrer dans un rêve",
	"Les aliments du moins au plus susceptibles de ruiner votre tenue",
	"Les pires aux meilleurs objets à oublier en allant à la salle de sport",
	"Les célébrités du moins au plus susceptibles de s'inviter à un mariage",
	"Les super-pouvoirs du moins au plus susceptibles de passer inaperçus",
	"Les choses que vous voulez le moins au plus trouver dans votre grenier",
	"Les personnages fictifs du moins au plus susceptibles de gagner un concours de danse",
	"Les animaux du moins au plus susceptibles de voler votre déjeuner",
	"Les pires aux meilleures excuses pour ne pas faire vos devoirs",
	"Les super-vilains du moins au plus susceptibles de devenir bons",
	"Les émissions de télévision du moins au plus susceptibles de vous rendre nostalgique",
	"Les pires aux meilleurs endroits pour se perdre",
	"Les objets fictifs du moins au plus utiles dans la vie réelle",
	"Les animaux du moins au plus susceptibles de dominer le monde",
	"Les pires aux meilleurs records du monde à battre",
	"Les événements historiques du moins au plus gênants à voir",
	"Les personnages fictifs du moins au plus susceptibles d'organiser une fête surprise",
	"Les pires aux meilleurs sons pour se réveiller",
	"Les célébrités du moins au plus susceptibles d'avoir une identité secrète",
	"Les aliments du moins au plus susceptibles d'être mal compris",
	"Les pires aux meilleures choses à porter à une fête costumée",
	"Les super-pouvoirs du moins au plus embarrassants",
	"Les choses que vous voulez le moins au plus marcher dessus pieds nus",
	"Les célébrités du moins au plus susceptibles de participer à un concours de talents",
	"Les pires aux meilleures choses à faire le jour de votre anniversaire",
	"Les choses que vous voulez le moins au plus trouver dans votre frigo",
	"Les créatures fictives du moins au plus susceptibles d'être réelles",
	"Les aliments du moins au plus susceptibles de ruiner un premier rendez-vous",
	"Les super-héros du moins au plus susceptibles de trop dormir",
	"Les pires aux meilleures raisons d'appeler malade",
	"Les univers fictifs du moins au plus confus",
	"Les aliments du moins au plus susceptibles de déclencher un débat",
	"Les super-pouvoirs du moins au plus susceptibles de se retourner contre vous",
	"Les choses que vous voulez le moins au plus voir dans une maison hantée",
	"Les célébrités du moins au plus susceptibles de faire une crise de colère",
	"Les pires aux meilleures choses à entendre dans un message vocal",
	"Les animaux du moins au plus susceptibles de gagner un concours de beauté",
	"Les personnages fictifs du moins au plus susceptibles de devenir une star de la télé-réalité",
	"Les aliments du moins au plus utiles dans une bataille de nourriture",
	"Les pires aux meilleurs endroits pour s'endormir accidentellement",
	"Les créatures fictives du moins au plus terrifiantes",
	"Les super-héros du moins au plus susceptibles de violer la loi",
	"Les pires aux meilleures raisons d'écrire une autobiographie",
	"Les aliments du moins au plus susceptibles d'être considérés comme 'exotiques'",
	"Les choses que vous voulez le moins au plus trouver sous votre lit",
	"Les super-pouvoirs du moins au plus susceptibles de créer le chaos",
	"Les figures historiques du moins au plus susceptibles d'apprécier la technologie moderne",
	"Les pires aux meilleures choses à entendre lors d'un premier rendez-vous",
	"Les célébrités du moins au plus susceptibles de devenir président",
	"Les super-vilains du moins au plus susceptibles de prendre leur retraite",
	"Les objets fictifs du moins au plus dangereux à utiliser",
	"Les pires aux meilleures choses à se produire lors d'une réunion de famille",
	"Les super-héros du moins au plus susceptibles de gagner un jeu télévisé",
	"Les choses que vous voulez le moins au plus perdre dans un lieu public",
	"Les personnages fictifs du moins au plus susceptibles d'être en retard",
	"Les pires aux meilleures excuses pour manquer un mariage",
	"Les aliments du moins au plus susceptibles de vous surprendre",
	"Les super-pouvoirs du moins au plus susceptibles d'être surestimés",
	"Du pire au meilleur adjectif pour décrire la personne à votre droite",
	"Du pire au meilleur plat à prendre en bivouac",
	"Du pire cauchemar au meilleur rêve ",
	"Du pire au meilleur entretien d'embauche ",
	"Du pire au meilleur 1er rencard",
	"De la pire à la meilleure façon de tricher à un examen",
	"De la pire à la meilleure façon quitter quelqu'un",
	"De la pire à la meilleure demande en mariage",
	"Du pire au meilleur plat à cuisiner pour une soirée chill",
	"Du pire au meilleur objet pour caler une table",
	"Du pire au meilleur objet objet pour tuer quelqu'un ",
	"Du pire au meilleur sujet de philosophie au bac",
	"De la pire à la meilleure raison de mentir sur son âge ",
	"Du pire à la meilleure célébrité avec qui être ami.e",
	"De l'animal du plus simple au plus compliqué à battre à la bagarre",
	"Du plus petit au plus gros moyen de transport",
	"Du plus petit au plus gros animal (ficif ou réèl)",
	"Du plus petit au plus gros objet",
	"De la moins gentille à la pire douleur",
	"De la pire à la meilleure couverture pour un espion ",
	"De la pire à la meilleure rencontre avec sa belle mère ou son beau père",
	"Du pire au meilleur souvenir d'enfance ",
	"Du pire à la meilleure chose à trouver dans son réfrigérateur",
	"De la pire à la meilleure résolution pour la nouvelle année ",
	"Du pire au meilleur pote",
	"Du pire au meilleur ingrédient à mettre sur une pizza",
	"Du pire au meilleur film à regarder lors d'un premier date ",
	"Du pire au meilleur plat à cuisiner lors d'un premier date ",
	"De la pire à la meilleure chanson pour un enterrement ",
	"De la pire à la meilleure activité à la plage",
	"Du pire au meilleur objet à prendre sur une île déserte",
	"Du pire au meilleur plat de cantine",
	"Du pire au meilleur mot dans le carnet",
	"Du pire au meilleur cadeau d'anniversaire",
	"De la pire à la meilleur raison de finir en garde à vue",
	"Du pire au meilleur collègue de crime (fictif ou non) pour cambrioler une banque",
	"Du pire au meilleur cadeau de naissance",
	"Du pire au meilleur gout découvrir en croquant dans un chocolat ",
	"Du pire au meilleur truc à utiliser quand t'as plus de PQ",
	"Du pire au meilleur endroit où être quand t'as envie d'aller aux to",
	"De la pire a la meilleur lettes d'amour ",
	"Du pire au meilleur tatouage ",
	"Du pire au meilleur thème de musée ",
	"De la pire à la meilleur façon de calmer un bébé qui pleure",
	"Du pire au meilleur discours de mariage",
	"Du pire au meilleur scénario de vacances ",
	"Du pire au meilleur objet à perdre",
	"De la pire à la meilleure raison d'être en retard à un entretien d'embauche ",
	"Du pire au meilleur plat à manger avec du ketchup",
	"Du pire au meilleur objet à trouver dans un grenier",
	"De la pire à la meilleur disquette pour draguer",
	"Du pire au meilleur véhicule à conduire lors d'une course poursuite ",
	"Du pire au meilleur dernier plat avant de mourir ",
	"Du pire au meilleur animal de compagnie ",
	"Du pire au meilleur titre film français (fictif ou non) ",
	"Du pire au meilleur duo de célébrité pour une musique",
	"Du pire au meilleur célébrité pour feat de rap ",
	"De la pire à la meilleure raison d'être en colère ",
	"De la pire à la meilleure chose à exposer dans son salon",
	"De la pire à la meilleure chose probable à voir dans le ciel ",
	"De la pire à la meilleure chose à faire pour se faire pardonner",
	"Du pire au meilleur sujet de thèse ",
	"Du pire au meilleur sujet de stage",
	"De la pire à la meilleure raison pour faire une heure de colle",
	"Du pire au meilleur cadeau pour la fête des mères",
	"Du pire au meilleur cadeau pour la fête des pères",
	"Du pire au meilleur matériau pour construire une maison",
	"Du pire au meilleur signe de gang",
	"Du pire au meilleur thème soirée déguisée ",
	"De la pire à la meilleur association universitaire ",
	"De la société fictive la plus confuse à la plus structurée (type Futurama/Rick et Morty (thème a réécrire)",
	"De la pire à la meilleur tendance de mode",
	"Du pire au meilleur compagnon de voyage fictif",
	"De la pire à la meilleure grimace",
];

// Fonction pour choisir une citation aléatoire et l'afficher avec les styles intégrés
function citationAleatoire() {
	const index = Math.floor(Math.random() * citations.length);
	document.getElementById("citation").innerHTML = citations[index];
}

// Fonction pour générer une couleur pastel aléatoire
function couleurPastelAleatoire() {
	const r = Math.floor(200 + Math.random() * 55); // Valeur entre 200 et 255
	const g = Math.floor(200 + Math.random() * 55); // Valeur entre 200 et 255
	const b = Math.floor(200 + Math.random() * 55); // Valeur entre 200 et 255
	return `rgb(${r}, ${g}, ${b})`;
}

// Fonction pour changer la citation et la couleur de fond
function actualiserCitation() {
	citationAleatoire();
	document.body.style.backgroundColor = couleurPastelAleatoire();
}

// Affiche une citation aléatoire et change la couleur de fond au chargement de la page
window.onload = actualiserCitation;
