g_synonymes = [
	["Douche", "Bain"],
	["Four", "Micro-ondes"],
	["Couteau", "Ciseaux"],
	["Tasse", "Verre"],
	["Assiette", "Bol"],
	["Lit", "Canapé"],
	["Table", "Bureau"],
	["Chaise", "Tabouret"],
	["Lampe", "Bougie"],
	["Téléphone", "Tablette"],
	["Télévision", "Ordinateur"],
	["Frigo", "Congélateur"],
	["Plaque de cuisson", "Barbecue"],
	["Lave-vaisselle", "Évier"],
	["Machine à laver", "Sèche-linge"],
	["Balai", "Aspirateur"],
	["Montre", "Réveil"],
	["Ventilateur", "Climatiseur"],
	["Livre", "Magazine"],
	["Cahier", "Carnet"],
	["Stylo", "Crayon"],
	["Clé", "Serrure"],
	["Sac", "Valise"],
	["Lunettes", "Lentilles"],
	["Rideau", "Store"],
	["Coussin", "Oreiller"],
	["Couverture", "Plaid"],
	["Tapis", "Moquette"],
	["Parapluie", "K-way"],
	["Miroir", "Vitre"],
	["Pinceau", "Rouleau"],
	["Marteau", "Maillet"],
	["Tournevis", "Perceuse"],
	["Échelle", "Escabeau"],
	["Torche", "Lampe frontale"],
	["Imprimante", "Scanner"],
	["Souris", "Clavier"],
	["Écouteurs", "Casque"],
	["Radio", "Enceinte"],
	["Bouteille", "Carafe"],
	["Poêle", "Casserole"],
	["Passoire", "Écumoire"],
	["Grille-pain", "Gaufrier"],
	["Livre de recettes", "Carnet de notes"],
	["Brosse à dents", "Fil dentaire"],
	["Savon", "Gel douche"],
	["Shampoing", "Après-shampoing"],
	["Serviette", "Gant de toilette"],
	["Rasoir", "Tondeuse"],
	["Déodorant", "Parfum"],
	["Crème", "Lotion"],
	["Veste", "Manteau"],
	["Chaussures", "Bottes"],
	["Chapeau", "Casquette"],
	["Écharpe", "Foulard"],
	["Short", "Pantalon"],
	["T-shirt", "Pull"],
	["Robe", "Jupe"],
	["Montre", "Bracelet connecté"],
	["Portefeuille", "Porte-monnaie"],
	["Lunettes de soleil", "Chapeau"],
	["Valise", "Sac à dos"],
	["Vélo", "Trottinette"],
	["Voiture", "Moto"],
	["Barque", "Kayak"],
	["Avion", "Hélicoptère"],
	["Train", "Tramway"],
	["Bus", "Métro"],
	["Balcon", "Terrasse"],
	["Jardin", "Cour"],
	["Arrosoir", "Tuyau d’arrosage"],
	["Pelle", "Râteau"],
	["Brouette", "Chariot"],
	["Gant", "Moufle"],
	["Tondeuse", "Taille-haie"],
	["Éponge", "Chiffon"],
	["Seau", "Bassine"],
	["Boîte", "Coffre"],
	["Radio-réveil", "Enceinte Bluetooth"],
	["Clavier", "Piano"],
	["Machine à café", "Bouilloire"],
	["Planche à découper", "Plateau"],
	["Livre", "E-book"],
	["Vélomoteur", "Scooter"],
	["Boussole", "GPS"],
	["Briquet", "Allumettes"],
	["Thermos", "Gourde"],
	["Horloge", "Chronomètre"],
	["Table à repasser", "Fer à repasser"],
	["Lunettes de natation", "Masque de plongée"],
	["Table pliante", "Chaise pliante"],
	["Caméra", "Appareil photo"],
	["Glacière", "Sac isotherme"],
	["Carnet de santé", "Dossier médical"],
	["Boîte à outils", "Trousse à pharmacie"],
	["Manche à balai", "Serpillière"],
	["Chaussettes", "Collants"],
	["Tente", "Hamac"],
	["Barbecue", "Plancha"],
	["Télécommande", "Manette de jeu"]
];
